### ISSUE TITLE
No .sql file after executing

### ISSUE THREAD

**Issue by edips** [geops/mdb-pgsql#1]
It works and process all mdb tables on terminal however there is no .sql file even I set to TMPDIR=/home/user dictionary.
its output:
root@edips:/home/edip/Desktop/SQL/deneme/sql# ./mdb-pgsql.sh test-database.mdb
begin;
set search_path to public;
set standard_conforming_strings=on;
create or replace function sqlite3_datetime(bigint) returns timestamp without time zone as $$
select (TIMESTAMP WITH TIME ZONE 'epoch ' + $1/1000 \* INTERVAL '1 second')::timestamp without time zone;
$$ language sql;
create or replace function sqlite3_datetime(integer) returns timestamp without time zone as $$
select (TIMESTAMP WITH TIME ZONE 'epoch ' + $1/1000 \* INTERVAL '1 second')::timestamp without time zone;
$$ language sql;

CREATE CAST (bigint AS timestamp without time zone) WITH FUNCTION sqlite3_datetime(bigint) AS ASSIGNMENT;
CREATE CAST (integer AS timestamp without time zone) WITH FUNCTION sqlite3_datetime(integer) AS ASSIGNMENT;
create table public."economics" ("id" integer, "month qty" double precision, "unit price" text, "tr (in mil)" text);
create table public."closeouts" ("qty" text, "whl sale" text, "savings" text, "price" text);
INSERT INTO public."economics" VALUES(1,1.0,'56.6550','56.6550');
INSERT INTO public."economics" VALUES(2,2.0,'54.1800','108.3600');
INSERT INTO public."economics" VALUES(3,3.0,'51.7050','155.1150');
INSERT INTO public."economics" VALUES(4,4.0,'49.2300','196.9200');
INSERT INTO public."economics" VALUES(5,5.0,'46.7550','233.7750');
INSERT INTO public."closeouts" VALUES('2','12.6','10%','11.34');
INSERT INTO public."closeouts" VALUES('2','12.6','10%','11.34');
INSERT INTO public."closeouts" VALUES('2','12.6','10%','11.34');
INSERT INTO public."closeouts" VALUES('2','37.5','5%','35.63');
INSERT INTO public."closeouts" VALUES('4','32.25','5%','30.64');
DROP CAST (bigint AS timestamp without time zone) CASCADE;
DROP CAST (integer AS timestamp without time zone) CASCADE;
drop function if exists sqlite3_datetime(bigint);
drop function if exists sqlite3_datetime(integer);

commit;

**Comment by AugustusKling** [comment]
That's the expected behaviour. The SQL for PostgreSQL is printed to the standard output an thus the readme states:

> The generated SQL will be written to the standard output. It is recommended
> to pipe it to a file.

If you want a SQL file, invoke the script like so: `./mdb-pgsql.sh test-database.mdb > test-database.sql`

**Comment by edips** [comment]
Thank you. I tryed a few scripts to convert mdb to Postgresql but I couldnt succeed with mdb data with turkish characters. Fortunately only this script can work smooth with even big mdb file with Turkish characters.
